# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZTG-o-wkZMmmUO7yVy5jvtOh1tl2WS4
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

"""#EDA

Input & Output

| Jenis | Variabel | Deskripsi |
|-------|----------|-----------|
| Input | **RM** | Rata-rata jumlah kamar per unit rumah |
| Input | **LSTAT** | Persentase penduduk berpenghasilan rendah di lingkungan (%) |
| Input | **PTRATIO** | Rasio murid terhadap guru di area tersebut |
| Output | **MEDV** | Estimasi harga median rumah (dalam USD) |

---
"""

df = pd.read_csv("https://raw.githubusercontent.com/RusdiansyahAlief19/boston-house-app/refs/heads/main/data/housing.csv")

df.head()

df.info()

df.describe()

df.isna().sum()

"""Tidak ada missing value"""

df[df.duplicated()]

"""Tidak ada duplicated value"""

import matplotlib.pyplot as plt
import seaborn as sns

for col in df.columns:
    plt.figure(figsize=(6,2))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot {col}")
    plt.show()

for col in df.columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outlier_count = len(
        df[(df[col] < lower) | (df[col] > upper)]
    )

    print(f"{col}: {outlier_count}")

"""#Preprocessing Data"""

X = df[['RM', 'LSTAT', 'PTRATIO']]
y = df['MEDV']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train.head()

X_test.head()

y_train.head()

y_test.head()

mean = X_train.mean()
std = X_train.std()

def zscore_norm (df, mean, std):
    return (df - mean) / std

X_train = zscore_norm(X_train, mean, std)
X_test = zscore_norm(X_test, mean, std)

print(X_train.mean())
print(X_train.std())

"""#Training"""

class RegresiLinearBerganda:

    def __init__(self,
                 learning_rate=0.01,
                 iterations=1000):

        self.lr = learning_rate
        self.iterations = iterations

    def fit(self, X, y):

        n_samples, n_features = X.shape

        self.weights = np.zeros(n_features)
        self.bias = 0

        self.loss_history = []

        for _ in range(self.iterations):

            y_pred = np.dot(X, self.weights) + self.bias

            dw = (1/n_samples) * np.dot(
                X.T,
                (y_pred - y)
            )

            db = (1/n_samples) * np.sum(
                y_pred - y
            )

            self.weights -= self.lr * dw
            self.bias -= self.lr * db

            mse = np.mean(
                (y - y_pred) ** 2
            )

            self.loss_history.append(mse)

    def predict(self, X):

        return np.dot(X, self.weights) + self.bias

model = RegresiLinearBerganda()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(y_pred)

"""#Evaluasi"""

def rmse(y_true, y_pred):
    return np.sqrt(np.mean((y_true - y_pred) ** 2))

def r2_score(y_true, y_pred):
    ss_res = np.sum((y_true - y_pred) ** 2)
    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)

    return 1 - (ss_res / ss_tot)

print("RMSE =", rmse(y_test, y_pred))
print("R²   =", r2_score(y_test, y_pred))

import matplotlib.pyplot as plt

plt.plot(model.loss_history)
plt.xlabel("Iteration")
plt.ylabel("MSE")
plt.title("Training Loss")
plt.show()

"""# Simpan Model"""

import joblib

joblib.dump(model, "boston_model.pkl")